import React, { useState, useEffect } from 'react';
import { Target, Sparkles, Plus, Trash2, CheckCircle2, Circle, RefreshCw, Wand2, Check } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../../contexts/AuthContext';
import { storageService } from '../../services/storageService';
import { generateAIDailyGoals, GoalItem, DailyGoalContext } from '../../services/aiService';
import { SubjectType } from '../../types';
import { SUBJECTS } from '../../constants';

export const AIDailyGoals: React.FC = () => {
  const { user, updateDailyGoals } = useAuth();
  const [newGoalText, setNewGoalText] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  const rawGoals = user?.dailyGoals || [];

  // Convert legacy or standard goals into rich GoalItem
  const goals: GoalItem[] = rawGoals.map((g, idx) => ({
    id: g.id || `goal-${idx}`,
    text: g.text,
    completed: !!g.completed,
    isAISuggested: (g as any).isAISuggested !== undefined ? (g as any).isAISuggested : g.text.includes('🎯') || g.text.includes('⏱️') || g.text.includes('⚡') || g.text.includes('🔥') || g.text.includes('🧪') || g.text.includes('📖')
  }));

  // Build context for AI planner
  const buildContext = (): DailyGoalContext => {
    const userSubs = user?.subjects && user.subjects.length > 0 
      ? user.subjects 
      : [SubjectType.PHYSICS, SubjectType.CHEMISTRY, SubjectType.MATH, SubjectType.ENGLISH];

    const masteryMap: Record<string, number> = {};
    const studyTimeMap: Record<string, number> = {};

    userSubs.forEach(sub => {
      masteryMap[sub] = storageService.getMastery(sub);
      studyTimeMap[sub] = storageService.getTotalFocusTimeMinutes(sub);
    });

    return {
      subjects: userSubs,
      classLevel: user?.classLevel,
      masteryMap,
      studyTimeMap,
      streakCount: user?.streak?.count || 1
    };
  };

  // Auto-generate AI goals on initial mount if today's goals list is empty
  useEffect(() => {
    if (goals.length === 0 && !hasAutoGenerated && !isGenerating) {
      setHasAutoGenerated(true);
      handleGenerateAIGoals(true);
    }
  }, [user?.id]);

  const handleGenerateAIGoals = async (append: boolean = false) => {
    setIsGenerating(true);
    try {
      const context = buildContext();
      const aiGoals = await generateAIDailyGoals(context);

      if (append && goals.length > 0) {
        // Filter out duplicates
        const existingTexts = new Set(goals.map(g => g.text.toLowerCase()));
        const uniqueAiGoals = aiGoals.filter(g => !existingTexts.has(g.text.toLowerCase()));
        updateDailyGoals([...goals, ...uniqueAiGoals]);
      } else {
        // Combine AI goals with any user-custom added goals
        const existingCustomGoals = goals.filter(g => !g.isAISuggested);
        updateDailyGoals([...aiGoals, ...existingCustomGoals]);
      }
    } catch (err) {
      console.error("Failed to generate AI daily goals:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleAddCustomGoal = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newGoalText.trim()) return;

    const customGoal: GoalItem = {
      id: `custom-goal-${Date.now()}`,
      text: newGoalText.trim(),
      completed: false,
      isAISuggested: false
    };

    updateDailyGoals([...goals, customGoal]);
    setNewGoalText('');
  };

  const toggleGoal = (id: string) => {
    updateDailyGoals(goals.map(g => g.id === id ? { ...g, completed: !g.completed } : g));
  };

  const removeGoal = (id: string) => {
    updateDailyGoals(goals.filter(g => g.id !== id));
  };

  const completedCount = goals.filter(g => g.completed).length;

  return (
    <div className="bg-surface border border-border/10 rounded-2xl p-6 shadow-sm space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/10 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-text-primary flex items-center gap-2">
              <Target className="w-5 h-5 text-blue-500" /> Daily Smart Objectives
            </h2>
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20 uppercase tracking-wider flex items-center gap-1">
              <Sparkles className="w-3 h-3" /> AI Decision Engine
            </span>
          </div>
          <p className="text-xs text-text-muted mt-0.5">
            AI automatically recommends what to study today based on your mastery & history. Add your own custom goals on top!
          </p>
        </div>

        {/* AI Auto-Decide Button */}
        <button
          onClick={() => handleGenerateAIGoals(false)}
          disabled={isGenerating}
          className="px-3.5 py-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white text-xs font-bold rounded-xl shadow-md transition-all flex items-center justify-center gap-2 shrink-0 disabled:opacity-50"
        >
          {isGenerating ? (
            <>
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              <span>Analyzing History...</span>
            </>
          ) : (
            <>
              <Wand2 className="w-3.5 h-3.5 text-blue-200" />
              <span>Auto-Decide with AI</span>
            </>
          )}
        </button>
      </div>

      {/* Progress Bar */}
      {goals.length > 0 && (
        <div className="space-y-1.5">
          <div className="flex justify-between items-center text-xs text-text-muted">
            <span className="font-semibold">Today's Goal Progress</span>
            <span className="font-mono font-bold text-text-primary">
              {completedCount} of {goals.length} Completed ({Math.round((completedCount / goals.length) * 100)}%)
            </span>
          </div>
          <div className="w-full bg-surfaceHighlight h-2 rounded-full overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${(completedCount / goals.length) * 100}%` }}
              className="h-full bg-gradient-to-r from-blue-500 to-emerald-500 rounded-full"
            />
          </div>
        </div>
      )}

      {/* Goal Addition Form */}
      <form onSubmit={handleAddCustomGoal} className="flex gap-2">
        <input
          type="text"
          value={newGoalText}
          onChange={(e) => setNewGoalText(e.target.value)}
          placeholder="Add your own custom task on top of AI recommendations..."
          className="flex-1 bg-surfaceHighlight border border-border/10 rounded-xl px-4 py-2.5 text-sm text-text-primary focus:outline-none focus:border-blue-500/50"
        />
        <button
          type="submit"
          disabled={!newGoalText.trim()}
          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2.5 rounded-xl font-bold text-xs shadow-sm transition disabled:opacity-50 flex items-center gap-1.5 shrink-0"
        >
          <Plus className="w-4 h-4" /> Add Goal
        </button>
      </form>

      {/* Goals List */}
      {isGenerating && goals.length === 0 ? (
        <div className="py-8 text-center text-text-muted space-y-2">
          <RefreshCw className="w-6 h-6 text-blue-500 animate-spin mx-auto" />
          <p className="text-sm font-medium">AI is evaluating your past quiz history & study logs...</p>
        </div>
      ) : goals.length === 0 ? (
        <div className="text-center py-8 border border-dashed border-border/15 rounded-xl space-y-3 bg-surfaceHighlight/30">
          <Target className="w-8 h-8 text-text-muted mx-auto opacity-50" />
          <p className="text-sm text-text-muted italic">No goals set for today.</p>
          <button
            onClick={() => handleGenerateAIGoals(false)}
            className="px-4 py-2 bg-blue-500/10 text-blue-600 dark:text-blue-400 font-bold text-xs rounded-xl hover:bg-blue-500/20 transition-colors inline-flex items-center gap-1.5"
          >
            <Sparkles className="w-3.5 h-3.5" /> Auto-Decide Today's Plan
          </button>
        </div>
      ) : (
        <div className="space-y-2">
          <AnimatePresence initial={false}>
            {goals.map((goal) => (
              <motion.div
                key={goal.id}
                layout
                initial={{ opacity: 0, y: 5 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, x: -10 }}
                className={`flex items-center justify-between p-3.5 rounded-xl border transition-all ${
                  goal.completed
                    ? 'bg-surfaceHighlight/60 border-border/5'
                    : 'bg-surface border-border/10 hover:border-border/20 shadow-sm'
                }`}
              >
                <button
                  onClick={() => toggleGoal(goal.id)}
                  className="flex items-center gap-3 flex-1 text-left min-w-0 mr-2"
                >
                  {goal.completed ? (
                    <CheckCircle2 className="w-5 h-5 text-emerald-500 shrink-0" />
                  ) : (
                    <Circle className="w-5 h-5 text-text-muted shrink-0 hover:text-blue-500 transition-colors" />
                  )}
                  <span
                    className={`text-sm leading-snug break-words ${
                      goal.completed ? 'text-text-muted line-through' : 'text-text-primary font-medium'
                    }`}
                  >
                    {goal.text}
                  </span>
                </button>

                <div className="flex items-center gap-2 shrink-0">
                  {goal.isAISuggested ? (
                    <span className="px-2 py-0.5 rounded-full text-[9px] font-bold bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20 flex items-center gap-1">
                      <Sparkles className="w-2.5 h-2.5" /> AI
                    </span>
                  ) : (
                    <span className="px-2 py-0.5 rounded-full text-[9px] font-bold bg-surfaceHighlight text-text-muted border border-border/10">
                      Custom
                    </span>
                  )}

                  <button
                    onClick={() => removeGoal(goal.id)}
                    className="p-1.5 text-text-muted hover:text-red-500 hover:bg-red-500/10 rounded-lg transition-colors"
                    title="Remove Goal"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      )}
    </div>
  );
};
